<?php

use Illuminate\Database\Seeder;
use App\Especialidades;
use App\Medico;
use App\Turno_espec_medic;

class Turno_espec_medicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 1)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 1)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '12:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 1)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 1)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '13:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 1)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 1)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '10:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 1)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 2)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '16:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = 'Turnos a domicilio 4612427';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 1)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 2)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '08:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = 'Turnos a domicilio 4612427';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 1)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 3)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = '';
        $p->horario = '';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 4)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '13:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$700";
        $p->otros = 'Turnos al 2215934885';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '08:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '08:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '18:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '09:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Sábado';
        $p->horario = '07:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 6)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '15:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 6)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '14:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 7)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '08:30';
        $p->pami = 'NO';
        $p->obra_social = "No atiende por IOMA";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();
   
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 7)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '08:30';
        $p->pami = 'NO';
        $p->obra_social = "No atiende por IOMA";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 8)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '09:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 8)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '09:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 8)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '09:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 9)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '16:20';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 9)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '16:20';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 9)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '16:20';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 10)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '09:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 2)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 10)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '13:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 3)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 11)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '14:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 3)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 11)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '15:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 3)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 12)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '13:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 3)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 12)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '11:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 3)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 12)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '13:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 4)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 13)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '12:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 4)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 14)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '12:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 4)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 14)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '12:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 5)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 15)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '18:00';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "$2000";
        $p->otros = '';
        $p->save();
             
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 16)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '17:00';
        $p->pami = 'NO';
        $p->obra_social = "Obras sociales por reintegro";
        $p->consulta_particular = "$1300";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 16)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes 8 hs';
        $p->horario = '08:00';
        $p->pami = 'NO';
        $p->obra_social = "Obras sociales por reintegro";
        $p->consulta_particular = "$1300";
        $p->otros = '';
        $p->save();  

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 16)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '17:00';
        $p->pami = 'NO';
        $p->obra_social = "Obras sociales por reintegro";
        $p->consulta_particular = "$1300";
        $p->otros = '';
        $p->save();
                     
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 16)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '08:00';
        $p->pami = 'NO';
        $p->obra_social = "Obras sociales por reintegro";
        $p->consulta_particular = "$1300";
        $p->otros = '';
        $p->save();
                             
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 16)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Sábado';
        $p->horario = '08:00';
        $p->pami = 'NO';
        $p->obra_social = "Obras sociales por reintegro";
        $p->consulta_particular = "$1300";
        $p->otros = '';
        $p->save();
                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 17)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '10:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA por cupo";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();
                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 6)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 17)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '10:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA por cupo";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();
          
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 7)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 18)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '12:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1400";
        $p->otros = '';
        $p->save();
          
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 8)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 19)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '13:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                  
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 8)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 19)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '17:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 9)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 20)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '18:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 10)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 21)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '12:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 10)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 21)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '17:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 10)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 21)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '17:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();
                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 11)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 22)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '14:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 11)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 22)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '08:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 11)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 22)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '14:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 12)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 23)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '12:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();

        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 13)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 24)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '13:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 14)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 25)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '14:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 14)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 25)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '17:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 14)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 25)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Sábado';
        $p->horario = '09:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 14)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 26)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '15:00';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 14)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 27)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '18:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                              
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 28)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '13:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                      
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 28)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '13:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 29)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '14:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 29)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '14:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono C";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 30)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Sábados';
        $p->horario = '09:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 31)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '09:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$1000";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 32)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '09:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$750";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 32)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '09:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$750";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 15)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 32)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '09:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$750";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 16)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 33)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '13:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 16)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 33)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '13:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$700";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 17)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 34)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '17:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 17)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 34)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '15:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 17)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 34)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '17:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 18)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 35)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '09:30';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 18)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 35)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '11:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 18)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 36)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '16:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 18)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 36)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '16:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$900";
        $p->otros = '';
        $p->save();
                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 19)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 37)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '18:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 19)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 37)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '15:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 19)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 37)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '18:00';
        $p->pami = 'NO';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 19)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 38)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '10:30';
        $p->pami = 'SI';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 39)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '08:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 39)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '08:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 39)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '08:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 39)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '08:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 40)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '16:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 40)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '16:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 41)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '16:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 41)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '08:30';
        $p->pami = '';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 42)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '08:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 42)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '13:30';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "$800";
        $p->otros = '';
        $p->save();
                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 43)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '16:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "$800";
        $p->otros = 'Turnos al 221 5658726';
        $p->save();
                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 44)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '16:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 44)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '16:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 44)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '15:30';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 44)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes';
        $p->horario = '15:30';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 45)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '07:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 45)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '14:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 45)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles';
        $p->horario = '07:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 45)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '14:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 46)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '07:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = 'Turnos al 4644546/5881 int 116';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 46)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '09:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = 'Turnos al 4644546/5881 int 116';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 20)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 46)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '07:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = 'Turnos al 4644546/5881 int 116';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 21)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 47)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'De Lunes a Viernes';
        $p->horario = '09:30';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 21)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 47)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'De Lunes a Viernes';
        $p->horario = '16:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 21)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 48)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'De Lunes a Viernes';
        $p->horario = '09:30';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 21)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 48)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'De Lunes a Viernes';
        $p->horario = '16:00';
        $p->pami = '';
        $p->obra_social = "IOMA bono B";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 21)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 31)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes';
        $p->horario = '13:30';
        $p->pami = '';
        $p->obra_social = "IOMA bono A";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 22)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 49)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes';
        $p->horario = '09:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 22)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 49)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves';
        $p->horario = '15:00';
        $p->pami = 'SI';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 50)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes de 8 a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 51)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes de 20 hs a Martes 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 51)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves de 20 hs a Viernes 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 27)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes de 8 a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 52)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes de 20 hs a Miércoles 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 53)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles de 8 a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 54)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércols de 20 hs a Jueves 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 54)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Sábados de 8 hs a Domingo 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 55)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves de 8 a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 56)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes de 8 a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 57)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes de 20 hs a Sábado 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 23)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 57)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Domingo de 8 hs a Lunes 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 1)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Lunes de 8 hs a Martes 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 1)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves 8 hs a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Martes de 8 hs a Miércoles 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Sábados de 8 hs a Domingo 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 5)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Domingo 20 hs a Lunes 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 58)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Miércoles 8 hs a Jueves 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 58)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Viernes 8 hs a Sábado 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                                
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 58)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Domingo 8 hs a 20 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                                        
        $p = new Turno_espec_medic();
        $especialidad = Especialidades::where('id', 24)->get()->first();
        $p->id_especialidades = $especialidad->id;
        $medico = Medico::where('id', 51)->get()->first();
        $p->id_medico = $medico->id;
        $p->dia = 'Jueves 20 hs a Viernes 8 hs';
        $p->pami = '';
        $p->obra_social = "";
        $p->consulta_particular = "";
        $p->otros = '';
        $p->save();
                                                                
    }
}
